services:
  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - .env
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    env_file:
      - .env
    command: server /data --console-address ":9001"
    volumes:
      - ./minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  filehosting:
    image: filehosting:latest
    ports:
      - "8080:8080" # HTTP
      - "50051:50051" # GRPC
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./configs:/app/configs
      - ./public:/app/public
