// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: file-hosting.proto

package filehosting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadFileRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Filename      string                    `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                    `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]*MetadataValue `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContentType   *string                   `protobuf:"bytes,4,opt,name=contentType,proto3,oneof" json:"contentType,omitempty"`
	Duration      *string                   `protobuf:"bytes,5,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_file_hosting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_hosting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_file_hosting_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UploadFileRequest) GetMetadata() map[string]*MetadataValue {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UploadFileRequest) GetContentType() string {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ""
}

func (x *UploadFileRequest) GetDuration() string {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return ""
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_file_hosting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_hosting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_file_hosting_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFileResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadFileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FileId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileId) Reset() {
	*x = FileId{}
	mi := &file_file_hosting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileId) ProtoMessage() {}

func (x *FileId) ProtoReflect() protoreflect.Message {
	mi := &file_file_hosting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileId.ProtoReflect.Descriptor instead.
func (*FileId) Descriptor() ([]byte, []int) {
	return file_file_hosting_proto_rawDescGZIP(), []int{2}
}

func (x *FileId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type File struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Filename      string                    `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                    `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ContentType   string                    `protobuf:"bytes,3,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Metadata      map[string]*MetadataValue `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_file_hosting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_file_hosting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_file_hosting_proto_rawDescGZIP(), []int{3}
}

func (x *File) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *File) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *File) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *File) GetMetadata() map[string]*MetadataValue {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FileMetadata struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MimeType      string                    `protobuf:"bytes,3,opt,name=mimeType,proto3" json:"mimeType,omitempty"`
	Sha1          string                    `protobuf:"bytes,4,opt,name=sha1,proto3" json:"sha1,omitempty"`
	CreatedAt     string                    `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ExpiredAt     string                    `protobuf:"bytes,6,opt,name=expiredAt,proto3" json:"expiredAt,omitempty"`
	BackupName    *string                   `protobuf:"bytes,7,opt,name=backupName,proto3,oneof" json:"backupName,omitempty"`
	Meta          map[string]*MetadataValue `protobuf:"bytes,8,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_file_hosting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_file_hosting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_file_hosting_proto_rawDescGZIP(), []int{4}
}

func (x *FileMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileMetadata) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileMetadata) GetSha1() string {
	if x != nil {
		return x.Sha1
	}
	return ""
}

func (x *FileMetadata) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *FileMetadata) GetExpiredAt() string {
	if x != nil {
		return x.ExpiredAt
	}
	return ""
}

func (x *FileMetadata) GetBackupName() string {
	if x != nil && x.BackupName != nil {
		return *x.BackupName
	}
	return ""
}

func (x *FileMetadata) GetMeta() map[string]*MetadataValue {
	if x != nil {
		return x.Meta
	}
	return nil
}

type MetadataValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataValue) Reset() {
	*x = MetadataValue{}
	mi := &file_file_hosting_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataValue) ProtoMessage() {}

func (x *MetadataValue) ProtoReflect() protoreflect.Message {
	mi := &file_file_hosting_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataValue.ProtoReflect.Descriptor instead.
func (*MetadataValue) Descriptor() ([]byte, []int) {
	return file_file_hosting_proto_rawDescGZIP(), []int{5}
}

func (x *MetadataValue) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Files struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      []*FileMetadata        `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Files) Reset() {
	*x = Files{}
	mi := &file_file_hosting_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Files) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Files) ProtoMessage() {}

func (x *Files) ProtoReflect() protoreflect.Message {
	mi := &file_file_hosting_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Files.ProtoReflect.Descriptor instead.
func (*Files) Descriptor() ([]byte, []int) {
	return file_file_hosting_proto_rawDescGZIP(), []int{6}
}

func (x *Files) GetMetadata() []*FileMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RenameFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=newName,proto3" json:"newName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameFileRequest) Reset() {
	*x = RenameFileRequest{}
	mi := &file_file_hosting_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFileRequest) ProtoMessage() {}

func (x *RenameFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_hosting_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFileRequest.ProtoReflect.Descriptor instead.
func (*RenameFileRequest) Descriptor() ([]byte, []int) {
	return file_file_hosting_proto_rawDescGZIP(), []int{7}
}

func (x *RenameFileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RenameFileRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

var File_file_hosting_proto protoreflect.FileDescriptor

const file_file_hosting_proto_rawDesc = "" +
	"\n" +
	"\x12file-hosting.proto\x12\vfilehosting\x1a\x1bgoogle/protobuf/empty.proto\"\xd1\x02\n" +
	"\x11UploadFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12H\n" +
	"\bmetadata\x18\x03 \x03(\v2,.filehosting.UploadFileRequest.MetadataEntryR\bmetadata\x12%\n" +
	"\vcontentType\x18\x04 \x01(\tH\x00R\vcontentType\x88\x01\x01\x12\x1f\n" +
	"\bduration\x18\x05 \x01(\tH\x01R\bduration\x88\x01\x01\x1aW\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.filehosting.MetadataValueR\x05value:\x028\x01B\x0e\n" +
	"\f_contentTypeB\v\n" +
	"\t_duration\"6\n" +
	"\x12UploadFileResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x18\n" +
	"\x06FileId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xf4\x01\n" +
	"\x04File\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12 \n" +
	"\vcontentType\x18\x03 \x01(\tR\vcontentType\x12;\n" +
	"\bmetadata\x18\x04 \x03(\v2\x1f.filehosting.File.MetadataEntryR\bmetadata\x1aW\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.filehosting.MetadataValueR\x05value:\x028\x01\"\xe0\x02\n" +
	"\fFileMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bmimeType\x18\x03 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04sha1\x18\x04 \x01(\tR\x04sha1\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\texpiredAt\x18\x06 \x01(\tR\texpiredAt\x12#\n" +
	"\n" +
	"backupName\x18\a \x01(\tH\x00R\n" +
	"backupName\x88\x01\x01\x127\n" +
	"\x04meta\x18\b \x03(\v2#.filehosting.FileMetadata.MetaEntryR\x04meta\x1aS\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.filehosting.MetadataValueR\x05value:\x028\x01B\r\n" +
	"\v_backupName\"'\n" +
	"\rMetadataValue\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\">\n" +
	"\x05Files\x125\n" +
	"\bmetadata\x18\x01 \x03(\v2\x19.filehosting.FileMetadataR\bmetadata\"=\n" +
	"\x11RenameFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\anewName\x18\x02 \x01(\tR\anewName2\x8b\x03\n" +
	"\vFileHosting\x12M\n" +
	"\n" +
	"UploadFile\x12\x1e.filehosting.UploadFileRequest\x1a\x1f.filehosting.UploadFileResponse\x121\n" +
	"\aGetFile\x12\x13.filehosting.FileId\x1a\x11.filehosting.File\x12A\n" +
	"\x0fGetFileMetadata\x12\x13.filehosting.FileId\x1a\x19.filehosting.FileMetadata\x126\n" +
	"\bGetFiles\x12\x16.google.protobuf.Empty\x1a\x12.filehosting.Files\x12D\n" +
	"\n" +
	"RenameFile\x12\x1e.filehosting.RenameFileRequest\x1a\x16.google.protobuf.Empty\x129\n" +
	"\n" +
	"DeleteFile\x12\x13.filehosting.FileId\x1a\x16.google.protobuf.EmptyB3Z1github.com/bruhabruh/file-hosting/pkg/filehostingb\x06proto3"

var (
	file_file_hosting_proto_rawDescOnce sync.Once
	file_file_hosting_proto_rawDescData []byte
)

func file_file_hosting_proto_rawDescGZIP() []byte {
	file_file_hosting_proto_rawDescOnce.Do(func() {
		file_file_hosting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_hosting_proto_rawDesc), len(file_file_hosting_proto_rawDesc)))
	})
	return file_file_hosting_proto_rawDescData
}

var file_file_hosting_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_file_hosting_proto_goTypes = []any{
	(*UploadFileRequest)(nil),  // 0: filehosting.UploadFileRequest
	(*UploadFileResponse)(nil), // 1: filehosting.UploadFileResponse
	(*FileId)(nil),             // 2: filehosting.FileId
	(*File)(nil),               // 3: filehosting.File
	(*FileMetadata)(nil),       // 4: filehosting.FileMetadata
	(*MetadataValue)(nil),      // 5: filehosting.MetadataValue
	(*Files)(nil),              // 6: filehosting.Files
	(*RenameFileRequest)(nil),  // 7: filehosting.RenameFileRequest
	nil,                        // 8: filehosting.UploadFileRequest.MetadataEntry
	nil,                        // 9: filehosting.File.MetadataEntry
	nil,                        // 10: filehosting.FileMetadata.MetaEntry
	(*emptypb.Empty)(nil),      // 11: google.protobuf.Empty
}
var file_file_hosting_proto_depIdxs = []int32{
	8,  // 0: filehosting.UploadFileRequest.metadata:type_name -> filehosting.UploadFileRequest.MetadataEntry
	9,  // 1: filehosting.File.metadata:type_name -> filehosting.File.MetadataEntry
	10, // 2: filehosting.FileMetadata.meta:type_name -> filehosting.FileMetadata.MetaEntry
	4,  // 3: filehosting.Files.metadata:type_name -> filehosting.FileMetadata
	5,  // 4: filehosting.UploadFileRequest.MetadataEntry.value:type_name -> filehosting.MetadataValue
	5,  // 5: filehosting.File.MetadataEntry.value:type_name -> filehosting.MetadataValue
	5,  // 6: filehosting.FileMetadata.MetaEntry.value:type_name -> filehosting.MetadataValue
	0,  // 7: filehosting.FileHosting.UploadFile:input_type -> filehosting.UploadFileRequest
	2,  // 8: filehosting.FileHosting.GetFile:input_type -> filehosting.FileId
	2,  // 9: filehosting.FileHosting.GetFileMetadata:input_type -> filehosting.FileId
	11, // 10: filehosting.FileHosting.GetFiles:input_type -> google.protobuf.Empty
	7,  // 11: filehosting.FileHosting.RenameFile:input_type -> filehosting.RenameFileRequest
	2,  // 12: filehosting.FileHosting.DeleteFile:input_type -> filehosting.FileId
	1,  // 13: filehosting.FileHosting.UploadFile:output_type -> filehosting.UploadFileResponse
	3,  // 14: filehosting.FileHosting.GetFile:output_type -> filehosting.File
	4,  // 15: filehosting.FileHosting.GetFileMetadata:output_type -> filehosting.FileMetadata
	6,  // 16: filehosting.FileHosting.GetFiles:output_type -> filehosting.Files
	11, // 17: filehosting.FileHosting.RenameFile:output_type -> google.protobuf.Empty
	11, // 18: filehosting.FileHosting.DeleteFile:output_type -> google.protobuf.Empty
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_file_hosting_proto_init() }
func file_file_hosting_proto_init() {
	if File_file_hosting_proto != nil {
		return
	}
	file_file_hosting_proto_msgTypes[0].OneofWrappers = []any{}
	file_file_hosting_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_hosting_proto_rawDesc), len(file_file_hosting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_hosting_proto_goTypes,
		DependencyIndexes: file_file_hosting_proto_depIdxs,
		MessageInfos:      file_file_hosting_proto_msgTypes,
	}.Build()
	File_file_hosting_proto = out.File
	file_file_hosting_proto_goTypes = nil
	file_file_hosting_proto_depIdxs = nil
}
