origin: http://localhost:8080/file
port: 8080
logger:
  level: info
  format: text
  addSource: false
  file:
    path: ""
    maxSizeInMB: 10
    maxBackups: 3
    maxAgeInDays: 14
    compress: false
fileStorage:
  basic:
    enabled: false
    path: files
  s3:
    enabled: true
    endpoint: localhost:9000
    region: ru-local
    bucket: files
    useSSL: false
rabbitmq:
  host: localhost
  port: 5672
