origin: http://localhost:8080/file
http:
  enabled: true
  allowPage: true
  port: 8080
grpc:
  enabled: true
  port: 50051
logger:
  level: info
  format: text
  addSource: false
  file:
    path: ""
    maxSizeInMB: 10
    maxBackups: 3
    maxAgeInDays: 14
    compress: false
fileStorage:
  basic:
    enabled: false
    path: files
  s3:
    enabled: true
    endpoint: minio:9000
    region: ru-local
    bucket: files
    useSSL: false
rabbitmq:
  host: rabbitmq
  port: 5672
